# Board dependent make definitions

# $Id$

# Copyright (C)2012-2015, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Board specific macro definitions

ifeq ($(BOARDNAME), EFM32_G8XX_STK)
MCU		= efm32g890f128
MCUSUBFAMILY	= EFM32G
CPUFLAGS	+= -mcpu=cortex-m3 -mthumb -DCORTEX_M3
FREERTOS_ARCH	= ARM_CM3
BOARDFLAGS	+= -DEFM32G890F128
BOARDFLAGS	+= -DEFM32_HFXO_FREQ=32000000UL
BOARDFLAGS	+= -DCONSOLE_PORT='"com1:115200,n,8,1"'
BOARDFLAGS	+= -DBUTTON1_PIN=GPIOPIN25 -DBUTTON1_INPUT=GPIOPIN25IN -DBUTTON1_ACTIVELOW
BOARDFLAGS	+= -DBUTTON2_PIN=GPIOPIN26 -DBUTTON2_INPUT=GPIOPIN26IN -DBUTTON2_ACTIVELOW
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN32 -DLED1_OUTPUT=GPIOPIN32OUT
BOARDFLAGS	+= -DLED2_PIN=GPIOPIN33 -DLED2_OUTPUT=GPIOPIN33OUT
BOARDFLAGS	+= -DLED3_PIN=GPIOPIN34 -DLED3_OUTPUT=GPIOPIN34OUT
BOARDFLAGS	+= -DLED4_PIN=GPIOPIN35 -DLED4_OUTPUT=GPIOPIN35OUT
OPENOCDIF	= jlink
OPENOCDIFSETUP	= -c "transport select swd"
endif

ifeq ($(BOARDNAME), EFM32G230F128_PROTOTYPE)
MCU		= efm32g230f128
MCUSUBFAMILY	= EFM32G
CPUFLAGS	+= -mcpu=cortex-m3 -mthumb -DCORTEX_M3
FREERTOS_ARCH	= ARM_CM3
BOARDFLAGS	+= -DEFM32G230F128
BOARDFLAGS	+= -DCONSOLE_PORT='"com4:115200,n,8,1"'
BOARDFLAGS	+= -DBUTTON1_PIN=GPIOPIN10 -DBUTTON1_INPUT=GPIOPIN10IN -DBUTTON1_ACTIVELOW
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN33 -DLED1_OUTPUT=GPIOPIN33OUT
OPENOCDIF	= jlink
OPENOCDIFSETUP	= -c "transport select swd"
endif
