# Board dependent make definitions

# Copyright (C)2013-2017, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Board specific macro definitions

ifeq ($(BOARDNAME), NUCLEO_F103RB)
MCU		= stm32f103rb
BOARDFLAGS	+= -DSTM32F103xB -DHSE_VALUE=8000000
BOARDFLAGS	+= -DBUTTON1_PIN=GPIOPIN45 -DBUTTON1_INPUT=GPIOPIN45IN -DBUTTON1_ACTIVELOW
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN5 -DLED1_OUTPUT=GPIOPIN5OUT
# The auxiliary serial port is USART3 on the Arduino expansion header pins D0 and D1
BOARDFLAGS	+= -DAUX_PORT='"com3:115200,n,8,1"'
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com2:115200,n,8,1"'
OPENOCDIF	= stlink-v2-1
endif

ifeq ($(BOARDNAME), OLIMEX_STM32_P103)
MCU		= stm32f103rb
BOARDFLAGS	+= -DSTM32F103xB -DHSE_VALUE=8000000
BOARDFLAGS	+= -DBUTTON1_PIN=GPIOPIN0 -DBUTTON1_INPUT=GPIOPIN0IN
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN44 -DLED1_OUTPUT=GPIOPIN44OUT -DLED1_ACTIVELOW
# The auxiliary serial port is USART1 on the UEXT header
BOARDFLAGS	+= -DAUX_PORT='"com1:115200,n,8,1"'
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com2:115200,n,8,1"'
endif

ifeq ($(BOARDNAME), OLIMEX_STM32_P107)
MCU		= stm32f107rb
BOARDFLAGS	+= -DSTM32F107xC -DHSE_VALUE=25000000
BOARDFLAGS	+= -DBUTTON1_PIN=GPIOPIN0 -DBUTTON1_INPUT=GPIOPIN0IN
BOARDFLAGS	+= -DBUTTON2_PIN=GPIOPIN45 -DBUTTON2_INPUT=GPIOPIN45IN -DBUTTON2_ACTIVELOW
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN38 -DLED1_OUTPUT=GPIOPIN38OUT
BOARDFLAGS	+= -DLED2_PIN=GPIOPIN39 -DLED2_OUTPUT=GPIOPIN39OUT
# The auxiliary serial port is USART2 on the UEXT header
BOARDFLAGS	+= -DAUX_PORT='"com2:115200,n,8,1"'
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com3:115200,n,8,1"'
endif
