name = "test_adc"
description = "SparkFun Pro Micro RP2040 ADC Test"
version = "1.0.0"

executables = ["test_adc"]

[[depends-on]]
embedded_rp2040 = "*"
rp2040_hal = "*"
rp2040_munts_lib = "*"

[configuration.values]
rp2040_hal.Use_Startup = false
rp2040_hal.Interrupts = "bb_runtimes"
embedded_rp2040.Max_CPUs = 2
embedded_rp2040.Board = "sparkfun_promicro"

[[actions]]
type = "post-build"
command = ["sh", "-c", "./postbuild.sh"]
