name=MuntsTech_ARM_Classes
version=1.0.0
author=Philip Munts <phil@munts.net>
maintainer=Philip Munts <phil@munts.net>
sentence=C++ classes for certain ARM microcontroller boards.
paragraph=Supported board families are RP2040, RP2350, and STM32.
category=Other
url=https://git.munts.com/arm-mcu
architectures=rp2040,stm32
depends=
includes=
