name = "test_adc"
description = "Seeed Studio Xiao RP2040 ADC Test"
version = "1.0.0"

executables = ["test_adc"]

[[depends-on]]
light_tasking_rp2040 = "*"
rp2040_hal = "^2"
rp2040_boards = "^2"
rp2040_usb_console = "^2"

[configuration.values]
rp2040_hal.Use_Startup = false
rp2040_hal.Interrupts = "bb_runtimes"
light_tasking_rp2040.Max_CPUs = 2
light_tasking_rp2040.Board = "generic_board"

[[actions]]
type = "post-build"
command = ["sh", "-c", "./postbuild.sh"]
