name=MuntsTech-Interfaces
version=1.0.0
author=Philip Munts <phil@munts.net>
maintainer=Philip Munts <phil@munts.net>
sentence=A collection of C++ abstract interfaces.
paragraph=Imported from the Linux Simple I/O Library (https://github.com/pmunts/libsimpleio).
category=Other
url=https://git.munts.com/arm-mcu
architectures=*
depends=
includes=
