name=MuntsTech_ARM
version=1.2.0
author=Philip Munts <phil@munts.net>
maintainer=Philip Munts <phil@munts.net>
sentence=Make files and classes for certain ARM microcontroller boards.
paragraph=Supported board families are RP2040, RP2350, and STM32.
category=Other
url=https://git.munts.com/arm-mcu/arduino
architectures=rp2040,stm32
depends=
includes=Arduino_ARM.h
