# Make definitions for ST-Link

# Copyright (C)2017-2026, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# ST Microelectronics STM32 Cube Programmer for Windows

FLASHFREQUENCY		?= 4000
FLASHPORT		?= SWD
FLASHWRITEADDR		?= 0x08000000

ifeq ($(findstring CYGWIN, $(shell uname)), CYGWIN)
STM32CUBEPROG		?= C:/PROGRA~1/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin/STM32_Programmer_CLI.exe
else
STM32CUBEPROG		?= STM32_Programmer_CLI
endif

STM32CUBEPROGOPTS	+= -c port=$(FLASHPORT) freq=$(FLASHFREQUENCY)

.SUFFIXES: .bin .flashstlink

# Program flash with ST-Link

.bin.flashstlink:
	$(STM32CUBEPROG) $(STM32CUBEPROGOPTS) -e all -w $< $(FLASHWRITEADDR) -hardRst
