#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("thermometer.Resource", IsApplication=true)]

namespace thermometer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int text = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int textbox = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int connectbutton = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int outputbox = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int servername = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int serverprompt = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int tempdisplay = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_label = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int app_label_long = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int button_connect = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int button_disconnect = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int server_hint = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int server_prompt = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int status_connected = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int status_connecting = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
