# Copyright (C)2019, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Optional definitions for certain development hosts

ifeq ($(shell uname), Darwin)
MBEDPREFIX	?= /Volumes
endif

ifeq ($(shell uname), Linux)
MBEDPREFIX	?= /media/$(USER)
endif

# Optional definitions for certain target boards

ifeq ($(BOARDNAME), FEZ)
FLASHSUFFIX	:= flashdfu
TARGETNAME	:= NUCLEO_F401RE
endif

ifeq ($(BOARDNAME), MBED_LPC1768)
# Original mbed LPC1768 board
MBEDCLIFLAGS	+= -DSERIAL_TX=P0_2 -DSERIAL_RX=P0_3
TARGETNAME	:= LPC1768
endif

ifeq ($(BOARDNAME), LPC4088_QUICKSTART)
# Embedded Artists LPC4088 QuickStart Board
MBEDCLIFLAGS	+= -DSERIAL_TX=P0_2 -DSERIAL_RX=P0_3
TARGETNAME	:= LPC4088
endif

ifeq ($(BOARDNAME), NUCLEO_F072RB)
MBEDDIR		?= $(MBEDPREFIX)/NUCLEO
endif

ifeq ($(BOARDNAME), NUCLEO_F103RB)
MBEDDIR		?= $(MBEDPREFIX)/NUCLEO
endif

ifeq ($(BOARDNAME), NUCLEO_F411RE)
MBEDDIR		?= $(MBEDPREFIX)/NODE_F411RE
endif

ifeq ($(BOARDNAME), NUCLEO_F446RE)
MBEDDIR		?= $(MBEDPREFIX)/NODE_F446RE
endif

ifeq ($(BOARDNAME), NUCLEO_L432KC)
MBEDDIR		?= $(MBEDPREFIX)/NODE_L432KC
endif
