name = "test_led"
description = "Seeed Studio Xiao RP2040 LED Test"
version = "1.0.0"

executables = ["test_led"]

[[depends-on]]
munts_rp2040_lib_embedded = "*"

[configuration.values]
rp2040_hal.Use_Startup = false
rp2040_hal.Interrupts = "bb_runtimes"
embedded_rp2040.Max_CPUs = 2
embedded_rp2040.Board = "generic_board"

[[actions]]
type = "post-build"
command = ["sh", "-c", "./postbuild.sh"]
